/**
 * 
 * 用户登录
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 部门简要
 */
export interface DepartmentSimple { 
    /**
     * 公司id
     */
    readonly companyId?: string;
    /**
     * 公司名称
     */
    readonly companyName?: string;
    /**
     * 部门id
     */
    readonly id?: string;
    /**
     * 部门名称
     */
    readonly name?: string;
}
