/**
 * 
 * 用户登录
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 错误信息
 */
export interface ErrorMsg { 
    readonly code?: number;
    readonly message?: string;
}