/**
 *
 * 用户登录
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {DepartmentSimple} from './departmentSimple';
import {UserSimple} from './userSimple';

/**
 * 登录结果
 */
export interface LoginResult {
  department?: DepartmentSimple;
  /**
   * 请求头Token
   */
  readonly headerToken?: string;
  /**
   * 最后登录时间
   */
  readonly latestLoginDateTime?: Date;
  /**
   * 菜单code
   */
  readonly menus?: Array<string>;
  /**
   * 操作code
   */
  readonly operators?: Array<string>;
  /**
   * 请求参数Token
   */
  readonly queryToken?: string;
  user?: UserSimple;
  system: boolean;
}
