/**
 * 
 * 用户登录
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 登录信息
 */
export interface Login { 
    /**
     * 密码
     */
    password: string;
    /**
     * 用户名
     */
    username: string;
}
