/**
 * 
 * 用户登录
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DepartmentSimple } from './departmentSimple';
import { UserSimple } from './userSimple';


/**
 * 登录结果
 */
export interface LoginResult { 
    /**
     * 部门信息
     */
    readonly department?: DepartmentSimple;
    /**
     * 请求头Token
     */
    readonly headerToken?: string;
    /**
     * 最后登录时间
     */
    readonly latestLoginDateTime?: Date;
    /**
     * 请求参数Token
     */
    readonly queryToken?: string;
    /**
     * 系统管理员
     */
    readonly system?: boolean;
    /**
     * 用户信息
     */
    readonly user?: UserSimple;
}
