/**
 * 
 * 组织机构
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 权限
 */
export interface Permission { 
    method: string;
    readonly name?: string;
    path: string;
}
