/**
 * 
 * 组织机构
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 权限
 */
export interface Permission { 
    readonly method: Permission.MethodEnum;
    readonly name?: string;
    readonly path?: string;
}
export namespace Permission {
    export type MethodEnum = 'POST' | 'GET' | 'HEAD' | 'DELETE' | 'PUT';
    export const MethodEnum = {
        POST: 'POST' as MethodEnum,
        GET: 'GET' as MethodEnum,
        HEAD: 'HEAD' as MethodEnum,
        DELETE: 'DELETE' as MethodEnum,
        PUT: 'PUT' as MethodEnum
    };
}