/**
 * 
 * 组织机构
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QuerySearchItemstring } from './querySearchItemstring';

/**
 * 检索
 */
export interface QuerySearchstring { 
    items?: Array<QuerySearchItemstring>;
    logic: QuerySearchstring.LogicEnum;
    searches?: Array<QuerySearchstring>;
}
export namespace QuerySearchstring {
    export type LogicEnum = 'AND' | 'OR' | 'NOT' | 'XOR';
    export const LogicEnum = {
        AND: 'AND' as LogicEnum,
        OR: 'OR' as LogicEnum,
        NOT: 'NOT' as LogicEnum,
        XOR: 'XOR' as LogicEnum
    };
}