/**
 * 
 * 组织机构
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 比较项
 */
export interface QuerySearchItemstring { 
    compare: QuerySearchItemstring.CompareEnum;
    name: QuerySearchItemstring.NameEnum;
    value: any;
}
export namespace QuerySearchItemstring {
    export type CompareEnum = 'EQ' | 'LT' | 'NE' | 'LE' | 'GT' | 'GE' | 'LIKE' | 'IN' | 'ISNULL' | 'NOTNULL';
    export const CompareEnum = {
        EQ: 'EQ' as CompareEnum,
        LT: 'LT' as CompareEnum,
        NE: 'NE' as CompareEnum,
        LE: 'LE' as CompareEnum,
        GT: 'GT' as CompareEnum,
        GE: 'GE' as CompareEnum,
        LIKE: 'LIKE' as CompareEnum,
        IN: 'IN' as CompareEnum,
        ISNULL: 'ISNULL' as CompareEnum,
        NOTNULL: 'NOTNULL' as CompareEnum
    };
    export type NameEnum = 'username';
    export const NameEnum = {
        Username: 'username' as NameEnum
    };
}
