/**
 * 
 * 组织机构
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 角色菜单操作
 */
export interface RoleMenuOperator { 
    /**
     * 菜单
     */
    menus?: Array<string>;
    /**
     * 操作
     */
    operators?: Array<string>;
}
