/**
 * 
 * 组织机构
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Permission } from './permission';

/**
 * 角色
 */
export interface RoleAdd { 
    menuCodes: Array<string>;
    name: string;
    operatorCodes: Array<string>;
    permissions: Array<Permission>;
}