/**
 * 
 * 用户登录
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 用户简要
 */
export interface UserSimple { 
    /**
     * 用户id
     */
    readonly id?: string;
    /**
     * 用户名
     */
    readonly username?: string;
}